id: A6896EBB2
title: 'The Profound Bestowal of Blessings: A Sādhana of Dorje Drolö from the Reality
  Ḍākinīs'' Secret Treasury (Chönyi Khandrö Sangdzö)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:29:16.154256
  last_modified_at: 2022-03-01 03:29:16.154259
