id: A6896EBB2
title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious Dorje
  Drolö'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:29:16.150548
  last_modified_at: 2022-03-01 03:29:16.150555
